version: "3.7"

services:
  db:
    image: postgres
  web:
    build: .
    volumes:
      - ./myproject:/work
    ports:
      - 8000:8000
    command: python manage.py runserver 0:8000
    depends_on:
      - db
